### ISSUE TITLE
Does this OS have English?

### ISSUE THREAD

**Issue by BH-Playz** [Metabolix/PutkaOS#1]
Does this OS have the English language? If yes, I will then closed this issue, If not, add it please.

**Comment by BH-Playz** [comment]
@Metabolix?

**Comment by Metabolix** [comment]
LOL. This OS was last updated in 2011 and it's not even really usable, just a hobbyist playground which doesn't yet support enough common interfaces to support almost any existing real-world apps. So no, there's no English, nor any other language, and nothing will ever be added to this completely abandoned and incomplete project.
